# 운영 환경 설정
spring:
  # MySQL 또는 PostgreSQL 사용 (운영용 DB)
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/office_commute}
    username: ${DB_USERNAME:office_user}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # 커넥션 풀 설정 (성능 최적화)
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA 운영 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 스키마 검증만, 변경 금지
    properties:
      hibernate:
        show_sql: false  # 성능을 위해 SQL 출력 안함
        dialect: org.hibernate.dialect.MySQLDialect
  
  # SQL 초기화 비활성화
  sql:
    init:
      mode: never  # 운영에서는 data.sql 실행 안함

# P6Spy 비활성화 (운영 성능을 위해)
decorator:
  datasource:
    p6spy:
      enable-logging: false

# 운영용 로깅 설정 (최소화)
logging:
  level:
    org.hibernate.SQL: error
    org.hibernate.type: error
    org.springframework.security: warn
    p6spy: off
    com.company.officecommute: info
    root: warn
  
  # 로그 파일 설정
  file:
    name: logs/office-commute.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# 운영용 API 설정 (환경변수 사용)
public:
  data:
    api:
      serviceKey: ${PUBLIC_API_SERVICE_KEY}
      url: ${PUBLIC_API_URL:http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo}

# 서버 포트 설정
server:
  port: ${SERVER_PORT:8080}